language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.4.0"

before_install:
  - wget "http://download.mono-project.com/archive/3.4.0/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

before_script:
- pwd
- ls

script:
 - ./build.sh
# - .ci/nunit.sh ./tests/NServiceKit.ServiceHost.Tests/bin/Release/NServiceKit.ServiceHost.Tests.dll /noshadow
# - .ci/nunit.sh ./tests/NServiceKit.Messaging.Tests/bin/Release/NServiceKit.Messaging.Tests.dll /noshadow
# - .ci/nunit.sh ./tests/NServiceKit.Common.Tests/bin/Release/NServiceKit.Common.Tests.dll /noshadow
# - .ci/nunit.sh ./tests/NServiceKit.Auth.Tests/bin/Release/NServiceKit.Auth.Tests.dll /noshadow
